name:                thns
version:             0.1.0.0
github:              "ynishi/thns"
license:             BSD3
author:              "Yutaka Nishimura"
maintainer:          "ytk.nishimura@gmail.com"
copyright:           "2019 Yutaka Nishimura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ynishi/thns#readme>

dependencies:
- base >= 4.7 && < 5
- containers < 1
- split < 1
- text >= 1.2 && < 2
- parsec
- servant-server
- servant-mock
- servant-js
- servant-options
- warp
- wai-cors
- http-types
- aeson
- QuickCheck
- stm

library:
  source-dirs: src

executables:
  thns-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thns
  thns-cli:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - thns
  thns-axios:
    main:                Main.hs
    source-dirs:         thns-axios
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - thns

tests:
  thns-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - thns
